import math
import re
import requests


class constant:
    TKK = '432247.1200919766'  # this value maybe change by google ,then we need update
    

def rshift(val, n):
    """python port for '>>>'(right shift with padding) """
    return (val % 0x100000000) >> n


def _xr(a, b):
    size_b = len(b)
    c = 0
    while c < size_b - 2:
        d = b[c + 2]
        d = ord(d[0]) - 87 if 'a' <= d else int(d)
        d = rshift(a, d) if '+' == b[c + 1] else a << d
        a = a + d & 4294967295 if '+' == b[c] else a ^ d

        c += 3
    return a


def acquire(text):
    a = []
    # Convert text to ints
    for i in text:
        val = ord(i)
        if val < 0x10000:
            a += [val]
        else:
            # Python doesn't natively use Unicode surrogates, so account for those
            a += [
                math.floor((val - 0x10000) / 0x400 + 0xD800),
                math.floor((val - 0x10000) % 0x400 + 0xDC00)
            ]

    b = constant.TKK
    d = b.split('.')
    b = int(d[0]) if len(d) > 1 else 0

    # assume e means char code array
    e = []
    g = 0
    size = len(text)
    while g < size:
        l = a[g]
        # just append if l is less than 128(ascii: DEL)
        if l < 128:
            e.append(l)
        # append calculated value if l is less than 2048
        else:
            if l < 2048:
                e.append(l >> 6 | 192)
            else:
                # append calculated value if l matches special condition
                if (l & 64512) == 55296 and g + 1 < size and \
                        a[g + 1] & 64512 == 56320:
                    g += 1
                    l = 65536 + ((l & 1023) << 10) + (a[g] & 1023)  # This bracket is important
                    e.append(l >> 18 | 240)
                    e.append(l >> 12 & 63 | 128)
                else:
                    e.append(l >> 12 | 224)
                e.append(l >> 6 & 63 | 128)
            e.append(l & 63 | 128)
        g += 1
    a = b
    for i, value in enumerate(e):
        a += value
        a = _xr(a, '+-a^+6')
    a = _xr(a, '+-3^+b+-f')
    a ^= int(d[1]) if len(d) > 1 else 0
    if a < 0:  # pragma: nocover
        a = (a & 2147483647) + 2147483648
    a %= 1000000  # int(1E6)

    return '{}.{}'.format(a, a ^ b)


def _get(url):
    headers = {"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
               'accept-encoding': 'gzip, deflate, br',
               'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8',
               "cookie": "NID=204=sYYAQphrOsMs6VlB24MtbvYCBc3CN1_f6W4J21n7bs9MVTRX85WF2GluwPC1lCQKksMIXRZOhn5-2JdvrDYs9EcKe_kzz3vm5ePjj5r-NMo1gs1GrncpEDJ-tLSeL1X5Es36h7fH6L27Yxjj_recQ4d3wpyP6P4O9TbwAAFmp68; _ga=GA1.3.1429404313.1601724427; _gid=GA1.3.710270604.1606460839",
               'pragma': 'no-cache',
               'sec-fetch-dest': 'document',
               'sec-fetch-mode': 'navigate',
               'sec-fetch-site': 'none',
               'sec-fetch-user': '?1',
               'upgrade-insecure-requests': '1',
               'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36',
               }
    try:
        res = requests.get(url, verify=True, headers=headers, timeout=3)
    except:
        return '', 404
    return res.text.encode('UTF-8').decode('UTF-8'), res.status_code


def _get_token_key(self):

    response = requests.get("https://translate.google.com/")
    print()
    print()
    with open('test.log', 'w') as f:
        print(response.text, file = f)
    print()
    print()
    tkk_expr = re.search("(tkk:.*?),", response.text)
    if not tkk_expr:
        raise ValueError(
            "Unable to find token seed! Did https://translate.google.com change?"
        )

    tkk_expr = tkk_expr.group(1)
    try:
        # Grab the token directly if already generated by function call
        result = re.search("\d{6}\.[0-9]+", tkk_expr).group(0)
    except AttributeError:
        # Generate the token using algorithm
        timestamp = calendar.timegm(time.gmtime())
        hours = int(math.floor(timestamp / 3600))
        a = re.search("a\\\\x3d(-?\d+);", tkk_expr).group(1)
        b = re.search("b\\\\x3d(-?\d+);", tkk_expr).group(1)

        result = str(hours) + "." + str(int(a) + int(b))

    return result


# refresh tkk key
def refresh_tkk():
    text, code = _get("https://translate.google.cn/")
    if code != 200:
        return False
    text = re.findall(r'tkk(.+?),', text)
    constant.TKK = re.sub(':|\'', '', text[0])
    return True
